[window]

opacity = 0.7

padding.x = 0
padding.y = 0

#decorations = "None"
decorations_theme_variant = "Dark"


[font]
	size = 7



[shell]
  program = "/bin/zsh"
#	args = ["-l", "-c", "tmux attach || tmux"]



[[keyboard.bindings]]
key = "Semicolon"
mods = "Alt"
action = "None"

